{% set version = "0.8" %}
{% set commit = "0eaa22b30a240fd81a975d7de4e6e9131fecf05b" %}

package:
  name: r-xmlschema
  version: {{ version }}

source:
  url: https://github.com/omegahat/XMLSchema/archive/{{ commit }}.tar.gz
  sha256: 1b713cd591e5184d15d984e05a4aed907c32a4989fb5f587b96aaa1967cad188

build:
  noarch: generic
  number: 1005
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcurl
    - r-xml
    - r-codetools
  run:
    - r-base
    - r-rcurl
    - r-xml
    - r-codetools

test:
  commands:
    - $R -e "library('XMLSchema')"  # [not win]
    - "\"%R%\" -e \"library('XMLSchema')\""  # [win]

about:
  home: https
  license: GPL-2.0-only
  # license_file: LICENSE
  summary: R package to work with XML Schema

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - ocefpaf
