appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: bT2CPS533VS7QPrw4Yq7V7f/9hYzJL/qrO7yCPTVW0TCJi1jyehWsvFt46BcCuCUNFv+KpW3cDh49+S62/4mf9w/girmnhQUwWRywB03lDpvZHaE2eAXBI19c7j5CyUjPeWRsdvc1LAcv0fqUEH4/BLRHWCeuVze3ffWntxSTeOzVIVBCq0y6vd9FVGO55V7G33xCYvRnFibdeCzUyF5DXwOTt40x+BrWGWI3RyLsOBmUyBxVq3q9uH9ok3P9bFix2zng1SdIav0Gp3eXKtUXz3yX5PUE8vVf9fw/oH/4Xxwv/7rqIgD+aks911/1Z9fXzc1Lu1Q8RndfUcJcjHYyTPjfmz9vfPaCvSM2B7Fwcxvn9HaEXodqHO3bWIxmlSGPht4t+TQXf4XcoAevpKDOPKcIPFpBhlnddZYg/GM7RAORjusJnOSRsUXt+gGfuDPEq+DMbaLuVgrV5EWTkG2OwEdg4OhmVY0JLGhXqrmTrsOGg7lfl7wxUE75bOcLVxVbG3GNsz9FYUZr4PqU+OQGbh6Kl9iQkiAgnWHlKYvJVWZ1wQQUykRhafqh8CFnWZ+ZZJkn5eYuV7ZfcAD+qDzaDTJNB1vDEYEkSKYPgAg5aVR7VEJ5uHWosk/KVK5aLxqbbdCRqG+Rt79OuKnuXjtyLRsSItj3QF6X12JBWBFqG4=
conda_forge_output_validation: false
